// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/blueimp-md5/blueimp-md5.d.ts
declare module 'blueimp-md5' {
    export function md5(value: string, key?: string, raw?: boolean): string;
}
