// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/ngbootbox/ngbootbox.d.ts
interface NgBootboxDialog {
	title?: string;
	message?: string;
	templateUrl?: string;
	locale?: string;
	callback?: () => any;
	onEscape?: () => any | boolean;
	show?: boolean;
	backdrop?: boolean;
	closeButton?: boolean;
	animate?: boolean;
	className?: string;
	size?: string;
	buttons?: BootboxButtonMap;
}

interface BootboxService {
	alert(msg: string): ng.IPromise<any>;
	confirm(msg: string): ng.IPromise<any>;
	prompt(msg: string): ng.IPromise<any>;
	customDialog(options: NgBootboxDialog): void;
	setDefaults(options: BootboxDefaultOptions): void;
	hideAll(): void;

	addLocale(name: string, values: BootboxLocaleValues): void;
	removeLocale(name: string): void;
	setLocale(name: string): void;
}

declare var $ngBootbox: BootboxService;
